language: bash

sudo: required

services:
  - docker

before_install:
  - docker pull koalaman/shellcheck
  - docker pull lukasmartinelli/hadolint
  - docker pull quay.io/continuouspipe/ubuntu16.04:latest

script:
  - bash ./test.sh
